---
title: "Serve_predict"
output: html_document
---
##1	目的
男子プロテニス協会が公開するトッププロ96名のサーブとリターンのデータを用いて、サーブとリターンそれぞれにおいての上位半数と下位半数の線形判別を行う。

##2	データの出所
Official Site of Men's Professional Tennis(2018/12/18)
(URL:https://www.atptour.com/)

##3 変数の確認
```{r}
library(readxl)
Tennis_FinalReport<-read_excel("/Users/keigo/Desktop/dataanalysis/Tennis_FinalReport.xlsx")
str(Tennis_FinalReport)
```

##4 データの一部の表示
```{r}
head(Tennis_FinalReport)
```

##5 サーブデータ基本分析
```{r}
boxplot(Tennis_FinalReport$"1st_Serve" ~ Tennis_FinalReport$"Serve_Group",data=Tennis_FinalReport)
boxplot(Tennis_FinalReport$"1st_Serve_Points_Won" ~ Tennis_FinalReport$"Serve_Group",data=Tennis_FinalReport)
boxplot(Tennis_FinalReport$"2nd_Serve_Points_Won" ~ Tennis_FinalReport$"Serve_Group",data=Tennis_FinalReport)
boxplot(Tennis_FinalReport$"Avg_Aces" ~ Tennis_FinalReport$"Serve_Group",data=Tennis_FinalReport)
boxplot(Tennis_FinalReport$"Avg_ Double_Faults" ~ Tennis_FinalReport$"Serve_Group",data=Tennis_FinalReport)
boxplot(Tennis_FinalReport$"1st_Serve_Return_Points_Won" ~ Tennis_FinalReport$"Serve_Group",data=Tennis_FinalReport)
boxplot(Tennis_FinalReport$"2nd_Serve_Return_Points_Won" ~ Tennis_FinalReport$"Serve_Group",data=Tennis_FinalReport)
boxplot(Tennis_FinalReport$"Break_Points_Converted" ~ Tennis_FinalReport$"Serve_Group",data=Tennis_FinalReport)
```

##6 サーブデータ判別分析
```{r}
library(MASS)
Serve_Group_Result<- lda(Tennis_FinalReport$"Serve_Group" ~ + Tennis_FinalReport$"1st_Serve" + Tennis_FinalReport$"1st_Serve_Points_Won" + Tennis_FinalReport$"2nd_Serve_Points_Won"  + Tennis_FinalReport$"Avg_Aces" + Tennis_FinalReport$"Avg_ Double_Faults" + Tennis_FinalReport$"1st_Serve_Return_Points_Won" + Tennis_FinalReport$"2nd_Serve_Return_Points_Won" + Tennis_FinalReport$"Break_Points_Converted",data=Tennis_FinalReport)
Serve_Group_Result
plot(Serve_Group_Result,dimen=1)
```

##7 サーブデータ判別分析
```{r}
library(MASS)
Serve_Group_Result<- lda(Tennis_FinalReport$"Serve_Group" ~ + Tennis_FinalReport$"1st_Serve" + Tennis_FinalReport$"1st_Serve_Points_Won" + Tennis_FinalReport$"2nd_Serve_Points_Won"  + Tennis_FinalReport$"Avg_Aces" + Tennis_FinalReport$"Avg_ Double_Faults" + Tennis_FinalReport$"1st_Serve_Return_Points_Won" + Tennis_FinalReport$"2nd_Serve_Return_Points_Won" + Tennis_FinalReport$"Break_Points_Converted",data=Tennis_FinalReport)
Serve_Group_Result
plot(Serve_Group_Result,dimen=1)
```

##8 サーブTOP48か否かの推定
```{r}
print(Serve_Group_Result$scaling)
Serve_Group_Predict<-predict(Serve_Group_Result,data=Tennis_FinalReport_Test)
str(Serve_Group_Predict)
```

####結果の整理
```{r}
if(nlevels(Serve_Group_Predict$class)==2)
  {hist(Serve_Group_Predict$x)}
if(nlevels(Serve_Group_Predict$class)>2)
  {plot(Serve_Group_Predict$x)}
```

